x-airflow-common: &airflow-common
  image: apache/airflow:2.10.4

  environment: &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor

    # 외부에 분리한 PostgreSQL 주소로 변경
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: ${AIRFLOW_DB_URL}

    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    AIRFLOW__CORE__FERNET_KEY: ""
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
    AIRFLOW__API__AUTH_BACKENDS: "airflow.api.auth.backend.basic_auth"

    _PIP_ADDITIONAL_REQUIREMENTS: ${_PIP_ADDITIONAL_REQUIREMENTS:-}

  volumes:
    - ../src/domains/airflow/dags:/opt/airflow/dags
    - ../src/domains/airflow/plugins:/opt/airflow/plugins
    - airflow-logs:/opt/airflow/logs

  user: "${AIRFLOW_UID:-50000}:0"

services:
  # 최초 실행 시 DB 마이그레이션 및 관리자 계정 생성
  airflow-init:
    <<: *airflow-common

    entrypoint: /bin/bash

    command:
      - -c
      - |
        airflow db migrate

        airflow users create \
          --username "${_AIRFLOW_WWW_USER_USERNAME:-airflow}" \
          --password "${_AIRFLOW_WWW_USER_PASSWORD:-airflow}" \
          --firstname Admin \
          --lastname User \
          --role Admin \
          --email admin@example.com || true

    environment:
      <<: *airflow-common-env

    restart: on-failure

  airflow-webserver:
    <<: *airflow-common

    command: webserver

    ports:
      - "8080:8080"

    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "--fail",
          "http://localhost:8080/health"
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

    restart: always

    depends_on:
      airflow-init:
        condition: service_completed_successfully

  airflow-scheduler:
    <<: *airflow-common

    command: scheduler

    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "--fail",
          "http://localhost:8974/health"
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

    restart: always

    depends_on:
      airflow-init:
        condition: service_completed_successfully

volumes:
  airflow-logs: