-- travel 업무 DB의 현재 서버 도메인 초기 스키마.
-- 각 객체는 없을 때만 생성하며, 기존 테이블의 구조와 데이터는 변경하지 않는다.

CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS area_code (
    area_code VARCHAR(5) PRIMARY KEY,
    name VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS category (
    code VARCHAR(12) PRIMARY KEY,
    depth SMALLINT NOT NULL,
    name VARCHAR(100) NOT NULL,
    parent_code VARCHAR(12)
);

CREATE TABLE IF NOT EXISTS sigungu_code (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    area_code VARCHAR(5) NOT NULL,
    name VARCHAR(50) NOT NULL,
    sigungu_code VARCHAR(5) NOT NULL,
    CONSTRAINT uk_sigungu_area_code UNIQUE (area_code, sigungu_code)
);

CREATE TABLE IF NOT EXISTS tourist_spot (
    content_id BIGINT PRIMARY KEY,
    addr1 VARCHAR(300),
    addr2 VARCHAR(200),
    collected_at TIMESTAMP(6),
    created_time TIMESTAMP(6),
    expguide TEXT,
    first_image TEXT,
    homepage TEXT,
    infocenter VARCHAR(200),
    map_level SMALLINT,
    map_x NUMERIC(13, 10),
    map_y NUMERIC(13, 10),
    parking TEXT,
    restdate TEXT,
    sigungu_code VARCHAR(5),
    title VARCHAR(200) NOT NULL,
    usetime TEXT,
    zipcode VARCHAR(10),
    content_type_id VARCHAR(5),
    ldong_regn_code VARCHAR(5),
    ldong_signgu_code VARCHAR(5),
    category INTEGER NOT NULL CHECK (category BETWEEN 1 AND 7),
    overview TEXT,
    detail_info JSONB NOT NULL DEFAULT jsonb_build_array()
);

CREATE TABLE IF NOT EXISTS spot_image (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_id BIGINT NOT NULL,
    image_url TEXT,
    "order" INTEGER NOT NULL,
    CONSTRAINT uk_spot_image_content_order UNIQUE (content_id, "order")
);

CREATE TABLE IF NOT EXISTS spot_embedding (
    content_id BIGINT PRIMARY KEY,
    created_at TIMESTAMP(6),
    embedding VECTOR(1536),
    input_text TEXT,
    keyword_text TEXT
);

CREATE TABLE IF NOT EXISTS etl_spot_state (
    content_id BIGINT PRIMARY KEY,
    embed_pending BOOLEAN NOT NULL DEFAULT true,
    last_etl_at TIMESTAMP(6) NOT NULL DEFAULT now(),
    content_hash VARCHAR(64) NOT NULL DEFAULT '',
    image_pending BOOLEAN NOT NULL DEFAULT true,
    image_absent BOOLEAN NOT NULL DEFAULT false,
    detail_common_pending BOOLEAN NOT NULL DEFAULT true,
    detail_intro_pending BOOLEAN NOT NULL DEFAULT true,
    detail_info_pending BOOLEAN NOT NULL DEFAULT true,
    overview TEXT
);

CREATE TABLE IF NOT EXISTS etl_run (
    run_id VARCHAR(250) NOT NULL,
    dag_id VARCHAR(250) NOT NULL,
    started_at TIMESTAMP NOT NULL DEFAULT now(),
    finished_at TIMESTAMP,
    status VARCHAR(20) NOT NULL DEFAULT 'running',
    stats JSONB NOT NULL DEFAULT '{}'::jsonb,
    PRIMARY KEY (dag_id, run_id)
);

CREATE INDEX IF NOT EXISTS idx_image_content
    ON spot_image (content_id);

CREATE INDEX IF NOT EXISTS idx_spot_category
    ON tourist_spot (category);

CREATE INDEX IF NOT EXISTS idx_spot_content_type
    ON tourist_spot (content_type_id);

CREATE INDEX IF NOT EXISTS idx_spot_ldong_region
    ON tourist_spot (ldong_regn_code, ldong_signgu_code);

CREATE INDEX IF NOT EXISTS idx_spot_sigungu
    ON tourist_spot (sigungu_code);

CREATE INDEX IF NOT EXISTS idx_state_image_recovery
    ON etl_spot_state (content_id)
    WHERE image_absent = false;
