-- 관광지 좋아요 기능 스키마
-- 1. tourist_spot / kakao_spot  like_count 캐시 컬럼 추가
-- 2. spot_like 테이블 신규 생성
--    - content_id(tourist_spot) 또는 kakao_spot_id 중 정확히 하나만 채워짐
--    - kakao_spot 삭제(DAG 감쇠 정리) 시 해당 좋아요 CASCADE DELETE

BEGIN;

-- ── 1. like_count 캐시 컬럼 ───────────────────────────────────────────────────
ALTER TABLE tourist_spot
    ADD COLUMN IF NOT EXISTS like_count INTEGER NOT NULL DEFAULT 0;

ALTER TABLE kakao_spot
    ADD COLUMN IF NOT EXISTS like_count INTEGER NOT NULL DEFAULT 0;

-- ── 2. spot_like 테이블 ───────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS spot_like (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT       NOT NULL,
    content_id      BIGINT,
    kakao_spot_id   BIGINT,
    created_at      TIMESTAMP(6) NOT NULL DEFAULT now(),

    CONSTRAINT chk_like_source CHECK (num_nonnulls(content_id, kakao_spot_id) = 1),
    CONSTRAINT fk_like_user    FOREIGN KEY (user_id)       REFERENCES users(user_id)            ON DELETE CASCADE,
    CONSTRAINT fk_like_tourist FOREIGN KEY (content_id)    REFERENCES tourist_spot(content_id),
    CONSTRAINT fk_like_kakao   FOREIGN KEY (kakao_spot_id) REFERENCES kakao_spot(id)            ON DELETE CASCADE
);

-- 사용자별 좋아요 목록 (cursor 기반 페이지네이션)
CREATE INDEX IF NOT EXISTS idx_like_user_created
    ON spot_like (user_id, id DESC);

-- 일반 관광지 중복 방지
CREATE UNIQUE INDEX IF NOT EXISTS uk_like_user_tourist
    ON spot_like (user_id, content_id) WHERE content_id IS NOT NULL;

-- 인기 관광지 중복 방지
CREATE UNIQUE INDEX IF NOT EXISTS uk_like_user_kakao
    ON spot_like (user_id, kakao_spot_id) WHERE kakao_spot_id IS NOT NULL;

COMMIT;
