-- 카카오 인기 장소의 대표 이미지 링크.
-- 이미지 원본은 저장·복제하지 않고, 기존 관광 데이터 또는 허용된 티스토리 원문이 제공한 URL만 보관한다.

BEGIN;

CREATE TABLE IF NOT EXISTS kakao_spot_image (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kakao_spot_id     BIGINT NOT NULL,
    tourist_content_id BIGINT,
    image_url         TEXT NOT NULL,
    source_doc_url    TEXT,
    source_site_name  VARCHAR(50) NOT NULL,
    source_type       VARCHAR(30) NOT NULL,
    collected_at      TIMESTAMP(6) NOT NULL DEFAULT now(),

    CONSTRAINT uk_kakao_spot_image UNIQUE (kakao_spot_id),
    CONSTRAINT ck_kakao_spot_image_source_type
        CHECK (source_type IN ('TOURIST_SPOT', 'TISTORY')),
    CONSTRAINT fk_kakao_spot_image_spot
        FOREIGN KEY (kakao_spot_id) REFERENCES kakao_spot(id) ON DELETE CASCADE,
    CONSTRAINT fk_kakao_spot_image_tourist
        FOREIGN KEY (tourist_content_id) REFERENCES tourist_spot(content_id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_kakao_spot_image_tourist
    ON kakao_spot_image (tourist_content_id)
    WHERE tourist_content_id IS NOT NULL;

COMMIT;
