-- 사용자 리뷰 기능: review, review_image 테이블 신규 생성 및 tourist_spot 별점 캐시 컬럼 추가.

BEGIN;

CREATE TABLE IF NOT EXISTS review (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_id  BIGINT       NOT NULL,
    user_id     BIGINT       NOT NULL,
    rating      SMALLINT     NOT NULL CHECK (rating BETWEEN 1 AND 5),
    body        TEXT,
    is_deleted  BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP(6) NOT NULL DEFAULT now(),
    updated_at  TIMESTAMP(6),

    CONSTRAINT fk_review_spot
        FOREIGN KEY (content_id) REFERENCES tourist_spot(content_id) ON DELETE CASCADE,
    CONSTRAINT fk_review_user
        FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    CONSTRAINT uk_review_user_spot
        UNIQUE (content_id, user_id)
);

CREATE TABLE IF NOT EXISTS review_image (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id     BIGINT       NOT NULL,
    image_url     TEXT         NOT NULL,
    display_order INTEGER      NOT NULL DEFAULT 0,
    created_at    TIMESTAMP(6) NOT NULL DEFAULT now(),

    CONSTRAINT fk_review_image_review
        FOREIGN KEY (review_id) REFERENCES review(id) ON DELETE CASCADE,
    CONSTRAINT uk_review_image_order
        UNIQUE (review_id, display_order)
);

ALTER TABLE tourist_spot
    ADD COLUMN IF NOT EXISTS avg_rating   NUMERIC(3, 2) NOT NULL DEFAULT 0.00,
    ADD COLUMN IF NOT EXISTS review_count INTEGER       NOT NULL DEFAULT 0;

CREATE INDEX IF NOT EXISTS idx_review_content
    ON review (content_id) WHERE is_deleted = FALSE;

CREATE INDEX IF NOT EXISTS idx_review_user
    ON review (user_id) WHERE is_deleted = FALSE;

CREATE INDEX IF NOT EXISTS idx_review_image_review
    ON review_image (review_id);

COMMIT;
