-- 카카오 블로그·카페 원천 문서 수집 이력.
-- 같은 도시·채널에서 같은 URL은 한 번만 형태소 분석·점수 반영한다.

BEGIN;

CREATE TABLE IF NOT EXISTS trend_source_document (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city_name          VARCHAR(20)  NOT NULL,
    channel            VARCHAR(10)  NOT NULL,
    source_url         TEXT         NOT NULL,
    published_at       TIMESTAMPTZ,
    first_collected_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    first_run_id       VARCHAR(250) NOT NULL,

    CONSTRAINT chk_trend_source_document_channel
        CHECK (channel IN ('blog', 'cafe')),
    CONSTRAINT uk_trend_source_document
        UNIQUE (city_name, channel, source_url)
);

CREATE INDEX IF NOT EXISTS idx_trend_source_document_collected
    ON trend_source_document (first_collected_at DESC);

COMMIT;
