-- 인기 관광지 트렌드 파이프라인 스키마
-- popular_spot_collection DAG / popular_spot_decay DAG 에서 사용하는 테이블을 추가한다.
--
-- 변경 사항
--   1. trending_spot  — 형태소 분석 중간 집계 (파이프라인 내부)
--   2. kakao_spot     — 카카오맵 검증 통과 장소 (사용자 노출)
--   3. spot_embedding — content_id 단독 PK → 서로게이트 PK + kakao_spot_id 지원
--
-- 적용 순서:
--   kakao_spot 테이블을 먼저 생성해야 spot_embedding FK 마이그레이션이 가능하다.
--
-- 실행:
--   psql $TRAVEL_DB_URL -v ON_ERROR_STOP=1 -f database/migrations/20260727_popular_spot_schema.sql

BEGIN;

-- ──────────────────────────────────────────────────────────────────────────────
-- 1. trending_spot
--    Kakao 검색 → 형태소 분석 결과를 도시·키워드 단위로 누적하는 중간 테이블.
--    카카오맵 검증을 통과한 것만 kakao_spot 으로 승격(promoted=true)된다.
-- ──────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS trending_spot (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    keyword         VARCHAR(100) NOT NULL,
    city_name       VARCHAR(20)  NOT NULL,
    blog_frequency  INTEGER      NOT NULL DEFAULT 0,
    cafe_frequency  INTEGER      NOT NULL DEFAULT 0,
    multi_channel   BOOLEAN      NOT NULL DEFAULT false,
    promoted        BOOLEAN      NOT NULL DEFAULT false,
    collected_at    TIMESTAMP(6) NOT NULL DEFAULT now(),

    CONSTRAINT uk_trending_keyword_city UNIQUE (keyword, city_name)
);

-- 클린업 / 최신 배치 조회용
CREATE INDEX IF NOT EXISTS idx_trend_collected
    ON trending_spot (collected_at);

-- 승격 필터 조회용
CREATE INDEX IF NOT EXISTS idx_trend_promoted
    ON trending_spot (promoted)
    WHERE promoted = false;


-- ──────────────────────────────────────────────────────────────────────────────
-- 2. kakao_spot
--    카카오맵 검증까지 통과한 장소만 저장되는 최종 산출물 테이블.
--    popularity_score 는 시간당 배치에서 누적 가산되며, 매일 자정 감쇠된다.
-- ──────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS kakao_spot (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kakao_place_id       VARCHAR(30)   NOT NULL,
    place_name           VARCHAR(200)  NOT NULL,
    city_name            VARCHAR(20)   NOT NULL,
    address_name         VARCHAR(300),
    category_group_code  VARCHAR(10)   NOT NULL,
    category_group_name  VARCHAR(50),
    longitude            DOUBLE PRECISION NOT NULL,
    latitude             DOUBLE PRECISION NOT NULL,
    blog_mention_count   INTEGER       NOT NULL DEFAULT 0,
    cafe_mention_count   INTEGER       NOT NULL DEFAULT 0,
    popularity_score     DOUBLE PRECISION NOT NULL DEFAULT 0,
    collected_at         TIMESTAMP(6)  NOT NULL DEFAULT now(),

    CONSTRAINT uk_kakao_place_id UNIQUE (kakao_place_id)
);

-- 도시별 인기순 조회 (사용자 노출)
CREATE INDEX IF NOT EXISTS idx_kakao_city_score
    ON kakao_spot (city_name, popularity_score DESC);

-- 카테고리별 감쇠 + 임계값 삭제 조회
CREATE INDEX IF NOT EXISTS idx_kakao_category
    ON kakao_spot (category_group_code);

-- 임계값 미만 삭제 조회
CREATE INDEX IF NOT EXISTS idx_kakao_score
    ON kakao_spot (popularity_score);


-- ──────────────────────────────────────────────────────────────────────────────
-- 3. spot_embedding 마이그레이션
--    기존: content_id BIGINT PRIMARY KEY (tourist_spot 전용)
--    변경: 서로게이트 PK 추가 + kakao_spot_id 컬럼 추가 (두 소스 통합 임베딩)
--
--    content_id 와 kakao_spot_id 중 정확히 하나만 값을 갖는다.
-- ──────────────────────────────────────────────────────────────────────────────

-- 3-1. 서로게이트 PK 컬럼 추가 (기존 데이터 보존)
ALTER TABLE spot_embedding
    ADD COLUMN IF NOT EXISTS embedding_id BIGINT GENERATED BY DEFAULT AS IDENTITY;

-- 3-2. content_id 를 nullable 로 변경하기 위해 PK 제약 해제
DO $$
BEGIN
    -- 이미 PK가 바뀐 환경에서 재적용해도 오류 없이 통과하도록 조건부 실행
    IF EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE table_name = 'spot_embedding'
          AND constraint_type = 'PRIMARY KEY'
          AND constraint_name = 'spot_embedding_pkey'
    ) THEN
        ALTER TABLE spot_embedding DROP CONSTRAINT spot_embedding_pkey;
    END IF;
END $$;

-- 3-3. 새 서로게이트 PK 설정
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE table_name = 'spot_embedding'
          AND constraint_type = 'PRIMARY KEY'
    ) THEN
        ALTER TABLE spot_embedding ADD CONSTRAINT spot_embedding_pkey PRIMARY KEY (embedding_id);
    END IF;
END $$;

-- 3-4. content_id nullable 전환
ALTER TABLE spot_embedding
    ALTER COLUMN content_id DROP NOT NULL;

-- 3-5. kakao_spot_id 컬럼 추가
ALTER TABLE spot_embedding
    ADD COLUMN IF NOT EXISTS kakao_spot_id BIGINT;

-- 3-6. 소스별 유니크 인덱스 (partial — 값이 있는 행에만 적용)
CREATE UNIQUE INDEX IF NOT EXISTS uk_spot_embedding_content
    ON spot_embedding (content_id)
    WHERE content_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uk_spot_embedding_kakao
    ON spot_embedding (kakao_spot_id)
    WHERE kakao_spot_id IS NOT NULL;

-- 3-7. 두 소스 중 정확히 하나만 채워지는 제약
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE table_name = 'spot_embedding'
          AND constraint_name = 'chk_spot_embedding_source'
    ) THEN
        ALTER TABLE spot_embedding
            ADD CONSTRAINT chk_spot_embedding_source
            CHECK (num_nonnulls(content_id, kakao_spot_id) = 1);
    END IF;
END $$;

-- 3-8. kakao_spot FK (CASCADE DELETE — kakao_spot 삭제 시 임베딩도 자동 삭제)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE table_name = 'spot_embedding'
          AND constraint_name = 'fk_spot_embedding_kakao'
    ) THEN
        ALTER TABLE spot_embedding
            ADD CONSTRAINT fk_spot_embedding_kakao
            FOREIGN KEY (kakao_spot_id) REFERENCES kakao_spot(id) ON DELETE CASCADE;
    END IF;
END $$;

COMMIT;
